version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --only main,docs
    - poetry run poetry-dynamic-versioning
    - poetry run sphinx-build -b dirhtml -d ./docs/_build/doctrees -W -E -T --keep-going ./docs ./_readthedocs/html


sphinx:
  builder: dirhtml
  configuration: "docs/conf.py"
  fail_on_warning: true
