version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --only main,docs,docs-ci
    - poetry run poetry-dynamic-versioning
    - poetry run task docs
    - mkdir ./_readthedocs
    - mv ./docs/_build/html ./_readthedocs


sphinx:
  builder: dirhtml
  configuration: "docs/conf.py"
  fail_on_warning: true
