[tool.poetry]
name = "mcproto"
version = "0.0.1a1"
description = "Library providing easy interactions with minecraft sevrers"
authors = ["ItsDrike <itsdrike@protonmail.com>"]
license = "MPL-2.0"

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
