name: Fragments check

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-fragment-added:
    if: github.event.pull_request.user.type != 'Bot' && !contains(github.event.pull_request.labels.*.name, 'skip-fragment-check')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # `towncrier check` runs `git diff --name-only origin/main...`, which
          # needs a non-shallow clone.
          fetch-depth: 0

      - name: Regular setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies using poetry
        run: poetry install --no-root --only release

      - name: Add poetry environment to path
        run: |
          echo "$(python -m poetry env info --path)/bin" >> $GITHUB_PATH
          python -m poetry -V

      - name: Check if changelog fragment was added
        run: |
          if ! towncrier check --compare-with origin/${{ github.base_ref }}; then
            echo "----------------------------------------------------"
            echo "Please refer to CONTRIBUTING.md/#Changelog and changes/README.md for more information"
            exit 1
          fi
