name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to prepare the release for"
        required: true

jobs:
  prepare-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      # Make the github application be the comitter
      # (see: https://stackoverflow.com/a/74071223 on how to obtain the comitter email)
      - name: Setup git config
        run: |
          git config --global user.name "py-mine-ci-bot"
          git config --global user.email "121461646+py-mine-ci-bot[bot]@users.noreply.github.com"

      - name: Setup python
        uses: actions/setup-python@v4
        id: python_setup
        with:
          python-version: 3.11

      - name: Python Dependency Caching
        uses: actions/cache@v3
        id: python_cache
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: "python-${{ runner.os }}-v1-${{ steps.python_setup.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}"

      - name: Install poetry
        shell: bash
        run: |
          pip install poetry

      - name: Install dependencies using poetry
        if: ${{ steps.python_cache.outputs.cache-hit }} == "true"
        shell: bash
        run: python -m poetry install --no-root --only release

      - name: Add poetry environment to path
        run: |
          echo "$(python -m poetry env info --path)/bin" >> $GITHUB_PATH
          python -m poetry -V

      - name: Checkout new branch
        run: git checkout -b "prepare-release-${{ github.event.inputs.version }}"

      - name: Run towncrier
        run: towncrier build --yes --version "${{ github.event.inputs.version }}"

      - name: Commit changes
        run: git commit -am "Prepare for release of version ${{ github.event.inputs.version }}"

      - name: Push changes
        run: git push origin "prepare-release-${{ github.event.inputs.version }}"

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          # We need to use a bot token to be able to trigger workflows that listen to pull_request calls
          github_token: ${{ steps.generate_token.outputs.token }}
          source_branch: prepare-release-${{ github.event.inputs.version }}
          destination_branch: main
          pr_assignee: ${{ github.event.sender.login }}
          pr_title: Prepare for release of ${{ github.event.inputs.version }}
          pr_label: "area: dependencies,type: release"
          pr_body: |
            Release preparation triggered by @${{ github.event.sender.login }}.
            Once the pull request is merged, you can trigger a PyPI release by creating a GitHub release for \`${{ github.event.inputs.version }}\` in the repository.
