name: Validation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        uses: ItsDrike/setup-poetry@v1
        with:
          python-version: 3.11
          poetry-version: 1.3.1
          install-args: "--without release"

      - name: Run pre-commit hooks
        run: SKIP=black,isort,flake8,slotscheck,codespell,pyright pre-commit run --all-files

      - name: Run black formatter check
        run: black --check --diff .

      - name: Run isort import formatter check
        run: isort --check --diff .

      - name: Run flake8 linter
        run: flake8 .

      - name: Run codespell linter
        run: codespell .

      - name: Run slotscheck
        run: slotscheck -m mcproto

      - name: Run pyright type checker
        run: pyright .
